export const ABI = [
  // ── Read ──────────────────────────────────────────────────────────────────
  { name: "admin",              type: "function", stateMutability: "view",       inputs: [],                                                                                inputs: [],       outputs: [{ type: "address" }] },
  { name: "requiredApprovals",  type: "function", stateMutability: "view",       inputs: [],                                                                                inputs: [],       outputs: [{ type: "uint16"  }] },
  { name: "trustedVerifiers",   type: "function", stateMutability: "view",       inputs: [{ name: "_v", type: "address" }],                                                  outputs: [{ type: "bool"    }] },
  { name: "verifierWeights",    type: "function", stateMutability: "view",       inputs: [{ name: "_v", type: "address" }],                                                  outputs: [{ type: "uint16"  }] },
  { name: "ATTR_NAME",          type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  { name: "ATTR_DOB",           type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  { name: "ATTR_SRN",           type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  { name: "ATTR_PRN",           type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  { name: "ATTR_EMAIL",         type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  { name: "ATTR_PHONE",         type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  { name: "ATTR_GOV_ID",        type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  { name: "ATTR_PHOTO",         type: "function", stateMutability: "view",       inputs: [],                                                                                outputs: [{ type: "bytes32" }] },
  {
    name: "getIdentity", type: "function", stateMutability: "view",
    inputs: [{ name: "_user", type: "address" }],
    outputs: [
      { name: "identityHash",      type: "bytes32" },
      { name: "ipfsCID",           type: "string"  },
      { name: "owner",             type: "address" },
      { name: "createdAt",         type: "uint256" },
      { name: "updatedAt",         type: "uint256" },
      { name: "isVerified",        type: "bool"    },
      { name: "isActive",          type: "bool"    },
      { name: "verificationLevel", type: "uint16"  },
      { name: "approvalWeight",    type: "uint16"  },
    ],
  },
  {
    name: "isVerifiedAndActive", type: "function", stateMutability: "view",
    inputs:  [{ name: "_user", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    name: "getAttribute", type: "function", stateMutability: "view",
    inputs:  [{ name: "_user", type: "address" }, { name: "_nameHash", type: "bytes32" }],
    outputs: [{ type: "bytes32" }],
  },
  {
    name: "attributeAccess", type: "function", stateMutability: "view",
    inputs:  [{ name: "", type: "address" }, { name: "", type: "address" }, { name: "", type: "bytes32" }],
    outputs: [{ type: "bool" }],
  },
  // ── Write ─────────────────────────────────────────────────────────────────
  {
    name: "registerIdentity", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_identityHash", type: "bytes32" }, { name: "_ipfsCID", type: "string" }],
    outputs: [],
  },
  {
    name: "updateIdentity", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_newIdentityHash", type: "bytes32" }, { name: "_newIpfsCID", type: "string" }],
    outputs: [],
  },
  { name: "revokeIdentity",   type: "function", stateMutability: "nonpayable", inputs: [],                                                                                                              outputs: [] },
  {
    name: "setAttribute", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_nameHash", type: "bytes32" }, { name: "_valueHash", type: "bytes32" }, { name: "_ipfsCID", type: "string" }],
    outputs: [],
  },
  {
    name: "grantAttributeAccess", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_service", type: "address" }, { name: "_nameHash", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "revokeAttributeAccess", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_service", type: "address" }, { name: "_nameHash", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "castVerificationVote", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_user", type: "address" }, { name: "_level", type: "uint16" }],
    outputs: [],
  },
  {
    name: "addTrustedVerifier", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_verifier", type: "address" }, { name: "_weight", type: "uint16" }],
    outputs: [],
  },
  {
    name: "removeTrustedVerifier", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_verifier", type: "address" }],
    outputs: [],
  },
  {
    name: "setRequiredApprovals", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_required", type: "uint16" }],
    outputs: [],
  },
  {
    name: "reactivateIdentity", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_user", type: "address" }],
    outputs: [],
  },
  {
    name: "adminRevokeIdentity", type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "_user", type: "address" }],
    outputs: [],
  },
  // ── Events ────────────────────────────────────────────────────────────────
  { name: "IdentityRegistered",     type: "event", inputs: [{ name: "user", type: "address", indexed: true }, { name: "identityHash", type: "bytes32", indexed: true }] },
  { name: "IdentityVerified",       type: "event", inputs: [{ name: "user", type: "address", indexed: true }, { name: "verificationLevel", type: "uint16" }] },
  { name: "IdentityRevoked",        type: "event", inputs: [{ name: "user", type: "address", indexed: true }] },
  { name: "VerificationVoteCast",   type: "event", inputs: [{ name: "user", type: "address", indexed: true }, { name: "verifier", type: "address", indexed: true }, { name: "newWeight", type: "uint16" }] },
  { name: "AttributeSet",           type: "event", inputs: [{ name: "user", type: "address", indexed: true }, { name: "nameHash", type: "bytes32", indexed: true }, { name: "valueHash", type: "bytes32" }, { name: "ipfsCID", type: "string" }] },
  { name: "AttributeAccessGranted", type: "event", inputs: [{ name: "user", type: "address", indexed: true }, { name: "service", type: "address", indexed: true }, { name: "nameHash", type: "bytes32", indexed: true }] },
  { name: "AttributeAccessRevoked", type: "event", inputs: [{ name: "user", type: "address", indexed: true }, { name: "service", type: "address", indexed: true }, { name: "nameHash", type: "bytes32", indexed: true }] },
] as const;
